# Generated by Django 5.2.5 on 2025-09-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=150, verbose_name='فرستنده')),
                ('receiver', models.CharField(max_length=150, verbose_name='گیرنده')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='متن پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و ساعت ارسال')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
